name: ADR Tools

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: reviewdoc/action-setup
      - run: reviewdog -version

  test:
    name: Test - ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Check results
        run: make
