name: ADR Tools

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    name: Test - ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Check results
        run: make
